#!/bin/csh -f
#
# This file will clean out any temporary Pro/E files which are
# not required.  Simply type "clean" in the desired directory 
# to clean it out. Or access it from the UTILITIES menu under
# MISC.
rm *.inf*
rm *.ger*
rm *.crc*
rm *.memb*
rm *.ers*
rm iges_stats.dat*
rm *.bde
rm *.bdi
rm *.bdm
rm *.m_p*
rm *.bom*
rm *.ptd
rm *.als
rm *.dat
rm *.pls
rm s2d0*.sec*
purge trail.\*

