
             REGRESSION TEST SUBMISSION FORM

All submissions must meet the following requirements:

 1. All file names, including period and extension, must be 28
    characters or less.  This includes objects created during
    the test, family table instances, etc.
 2. The test name must be unique to the system.
 4. Prior to submission, run the test on SUN, SGI, IBM, DECSTATION, HP700. 
 5. If possible, run the test on VAX.
 6. If the test is a customer demo, make sure all file names are
    unique across all demos.
 7. All objects stored during the test must be named explicitly. Do not
    accept default names (i.e. prt0001).
 8. The trail file can not depend on user name or machine name.
------------------------------------------------------------------------------

!-------------------------------------------------------------------------------
!
! TITLE: Assembly Design Demo
!
! DATE: Aug-29-1996
!
! SUBMITTED BY: Corrin DeBettencourt
!
! VERSION: G-03-21
!
! FILENAME: asmdes17.txt
!
! ADDITIONAL TRAIL FILES (IN ORDER):
!
! asmdesshd17.txt
! setup17.txt
!
! FILETYPE: PRODUCTION
!
! TEST CATEGORY: NEWDEMOS
!
! MODULE: ASSEMBLY
!
! KEYWORD: MISC
!
! LENGTH (IN LINES): 2620
!
! APPROXIMATE RUN TIME: 10 minutes on sun4_solaris
!
! REPLACES TEST: asmdes15
!
! OBJECTS REQUIRED FOR THIS TEST:
!
!  asmdes17.sub
!  auto.txt.entry
!  auto.txt.entry.dll
!  ball_bearing.asm
!  boot.asm
!  color.map
!  config.pro
!  corrin.int
!  gear_calc.lay
!  gear_levers.asm
!  gear_set.asm
!  low_gear.asm
!  mybomstyle.fmt
!  parts/ball.prt
!  parts/bolt.prt
!  parts/boot.prt
!  parts/boot_2.prt
!  parts/boot_smooth.prt
!  parts/cluster_countershaft.prt
!  parts/countershaft.prt
!  parts/cs_gear.prt
!  parts/fork_2_h.prt
!  parts/gear_lever.prt
!  parts/gear_lever_st.prt
!  parts/gear_skeleton.prt
!  parts/hex_cap_screw.prt
!  parts/hex_nut.prt
!  parts/inner_bb.prt
!  parts/knob.prt
!  parts/low_gear.prt
!  parts/low_rev_gear.prt
!  parts/main_shaft.prt
!  parts/ms_sec_gear.prt
!  parts/outer_bb.prt
!  parts/pin_gear.prt
!  parts/pinion_shaft.prt
!  parts/rev_gear_b.prt
!  parts/rev_gear_c.prt
!  parts/rev_shaft.prt
!  parts/sec_gear.prt
!  parts/shift_fork.prt
!  parts/shift_rod_end.prt
!  parts/shift_rod_r_l.prt
!  parts/shifter2.prt
!  parts/speedometer.prt
!  parts/spring.prt
!  parts/spring_cover.prt
!  parts/spring_seat_2.prt
!  parts/top_cover.prt
!  parts/trans_housing.prt
!  parts/washer.prt
!  pro_stds/README.txt
!  pro_stds/clean
!  pro_stds/configs/config.pro
!  pro_stds/configs/english.dtl
!  pro_stds/configs/menu_def.pro
!  pro_stds/configs/metric.dtl
!  pro_stds/configs/shd_surf_no.pro
!  pro_stds/configs/shd_surf_yes.pro
!  pro_stds/configs/silh_off.pro
!  pro_stds/configs/silh_on.pro
!  pro_stds/configs/tol_off.dtl
!  pro_stds/configs/tol_on.dtl
!  pro_stds/format_dir/al.frm
!  pro_stds/format_dir/ap.frm
!  pro_stds/format_dir/c_bom.frm
!  pro_stds/format_dir/csize.frm
!  pro_stds/format_dir/csize_top.frm
!  pro_stds/menu_def.pro
!  pro_stds/start_files/startassy.asm
!  pro_stds/start_files/startpart.prt
!  pro_stds/start_files/startshmtl.prt
!  pro_stds/templates/template.drw
!  shifter.asm
!  shifter_assembly.drw
!  transmission.asm
!
! OBJECTS FROM OTHER TESTS REQUIRED FOR THIS TEST:
!
!
! QCR'S REQUIRED FOR THIS TEST:
!
!
! TEST DESCRIPTION:
!
!  This is the 17.0 Assembly Design Demo
!
!
! MODIFICATIONS:
!
!-------------------------------------------------------------------------------

#REG #g03
#AUTOENTRY#peking:/peking/user/corrin/demos/g0321/asmdes17/auto.txt.entry
peking:/peking/user/corrin/demos/g0321/asmdes17/asmdes17.txt
peking:/peking/user/corrin/demos/g0321/asmdes17/asmdesshd17.txt
peking:/peking/user/corrin/demos/g0321/asmdes17/setup17.txt
#REG #obj
peking:/peking/user/corrin/demos/g0321/asmdes17/asmdes17.sub
peking:/peking/user/corrin/demos/g0321/asmdes17/auto.txt.entry
peking:/peking/user/corrin/demos/g0321/asmdes17/auto.txt.entry.dll
peking:/peking/user/corrin/demos/g0321/asmdes17/ball_bearing.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/boot.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/color.map
peking:/peking/user/corrin/demos/g0321/asmdes17/config.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/corrin.int
peking:/peking/user/corrin/demos/g0321/asmdes17/gear_calc.lay
peking:/peking/user/corrin/demos/g0321/asmdes17/gear_levers.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/gear_set.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/low_gear.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/mybomstyle.fmt
peking:/peking/user/corrin/demos/g0321/asmdes17/shifter.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/shifter_assembly.drw
peking:/peking/user/corrin/demos/g0321/asmdes17/transmission.asm
#OBJSUBDIR  #./parts
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/ball.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/bolt.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/boot.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/boot_2.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/boot_smooth.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/cluster_countershaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/countershaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/cs_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/fork_2_h.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/gear_lever.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/gear_lever_st.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/gear_skeleton.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/hex_cap_screw.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/hex_nut.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/inner_bb.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/knob.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/low_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/low_rev_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/main_shaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/ms_sec_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/outer_bb.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/pin_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/pinion_shaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/rev_gear_b.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/rev_gear_c.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/rev_shaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/sec_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shift_fork.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shift_rod_end.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shift_rod_r_l.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shifter2.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/speedometer.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/spring.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/spring_cover.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/spring_seat_2.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/top_cover.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/trans_housing.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/washer.prt
#OBJSUBDIR  #./pro_stds
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/README.txt
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/clean
#OBJSUBDIR  #./pro_stds/configs
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/config.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/english.dtl
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/menu_def.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/metric.dtl
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/shd_surf_no.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/shd_surf_yes.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/silh_off.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/silh_on.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/tol_off.dtl
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/tol_on.dtl
#OBJSUBDIR  #./pro_stds/format_dir
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/al.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/ap.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/c_bom.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/csize.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/csize_top.frm
#OBJSUBDIR  #./pro_stds
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/menu_def.pro
#OBJSUBDIR  #./pro_stds/start_files
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/start_files/startassy.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/start_files/startpart.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/start_files/startshmtl.prt
#OBJSUBDIR  #./pro_stds/templates
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/templates/template.drw


 
SUBMISSION LIST FILE: /peking/user/corrin/demos/g0321/asmdes17/asmdes17.sub
 
SUBMISSION NUMBER : 4914
 
#REG #g03
#AUTOENTRY#peking:/peking/user/corrin/demos/g0321/asmdes17/auto.txt.entry
peking:/peking/user/corrin/demos/g0321/asmdes17/asmdes17.txt
peking:/peking/user/corrin/demos/g0321/asmdes17/asmdesshd17.txt
peking:/peking/user/corrin/demos/g0321/asmdes17/setup17.txt
#REG #obj
peking:/peking/user/corrin/demos/g0321/asmdes17/asmdes17.sub
peking:/peking/user/corrin/demos/g0321/asmdes17/auto.txt.entry
peking:/peking/user/corrin/demos/g0321/asmdes17/auto.txt.entry.dll
peking:/peking/user/corrin/demos/g0321/asmdes17/ball_bearing.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/boot.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/color.map
peking:/peking/user/corrin/demos/g0321/asmdes17/config.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/corrin.int
peking:/peking/user/corrin/demos/g0321/asmdes17/gear_calc.lay
peking:/peking/user/corrin/demos/g0321/asmdes17/gear_levers.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/gear_set.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/low_gear.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/mybomstyle.fmt
peking:/peking/user/corrin/demos/g0321/asmdes17/shifter.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/shifter_assembly.drw
peking:/peking/user/corrin/demos/g0321/asmdes17/transmission.asm
#OBJSUBDIR  #./parts
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/ball.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/bolt.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/boot.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/boot_2.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/boot_smooth.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/cluster_countershaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/countershaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/cs_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/fork_2_h.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/gear_lever.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/gear_lever_st.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/gear_skeleton.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/hex_cap_screw.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/hex_nut.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/inner_bb.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/knob.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/low_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/low_rev_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/main_shaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/ms_sec_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/outer_bb.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/pin_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/pinion_shaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/rev_gear_b.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/rev_gear_c.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/rev_shaft.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/sec_gear.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shift_fork.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shift_rod_end.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shift_rod_r_l.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/shifter2.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/speedometer.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/spring.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/spring_cover.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/spring_seat_2.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/top_cover.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/trans_housing.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/parts/washer.prt
#OBJSUBDIR  #./pro_stds
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/README.txt
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/clean
#OBJSUBDIR  #./pro_stds/configs
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/config.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/english.dtl
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/menu_def.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/metric.dtl
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/shd_surf_no.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/shd_surf_yes.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/silh_off.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/silh_on.pro
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/tol_off.dtl
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/configs/tol_on.dtl
#OBJSUBDIR  #./pro_stds/format_dir
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/al.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/ap.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/c_bom.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/csize.frm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/format_dir/csize_top.frm
#OBJSUBDIR  #./pro_stds
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/menu_def.pro
#OBJSUBDIR  #./pro_stds/start_files
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/start_files/startassy.asm
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/start_files/startpart.prt
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/start_files/startshmtl.prt
#OBJSUBDIR  #./pro_stds/templates
peking:/peking/user/corrin/demos/g0321/asmdes17/pro_stds/templates/template.drw
